# Generated by Django 4.2.23 on 2025-08-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverable',
            old_name='benefit',
            new_name='benefitID',
        ),
    ]
