# Generated by Django 4.2.23 on 2025-07-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_app', '0002_alter_task_end_date_alter_task_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.CharField(default='1 day', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible_team',
            field=models.CharField(default='Unassigned', max_length=255),
        ),
    ]
