# Generated by Django 4.2.23 on 2025-08-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm_app', '0004_task_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deliverable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pm_app.deliverable'),
        ),
    ]
